[package]
name = "libre-oneroster"
version = "0.1.0"
authors = ["fffnite <bradley.whiteford@live.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
surf = "2.1"
tide = "0.16"
async-std = "1.6"
chrono = "0.4"
serde = "1.0"
log = "0.4"
env_logger = "0.7"
clap = "3.0.0-beta.2"
