name: libre oneroster
on: [push]
jobs:
  build:
    if: startsWith(github.ref, '/refs/tags/') != true
    runs-on: nix
    container:
      image: git.bgw.dev/bgw/nix-act:2.16.1
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ github.ref_type }}
      - run: nix build

  push:
    if: startsWith(github.ref, '/refs/tags/')
    runs-on: nix
    container:
      image: git.bgw.dev/bgw/nix-act:2.16.1
    steps:
      - uses: actions/checkout@v3
      - run: nix run .#dockerPush
        env:
          CI_PACKAGE_WRITE: ${{ secrets.CI_PACKAGE_WRITE }}
